{{- if (include "penpalmap-front.google.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpalmap-front.google.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "penpalmap-front.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "penpalmap-front.google.clientIdKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.google.clientId (empty .Values.config.google.clientId) }}
  {{ include "penpalmap-front.google.secretIdKey" . }}: {{ ternary (randAlphaNum 12) .Values.config.google.secretId (empty .Values.config.google.secretId) }}
{{- end }}