volumes:
  postgresql-data:
  penpalmap-api-data:

services:
  postgresql:
    build: ./docker/postgresql
    environment:
      POSTGRESQL_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/bitnami/postgresql
      - ./docker/postgresql/scripts:/docker-entrypoint-initdb.d

  penpalmap-api:
    image: ghcr.io/penpalmap/penpalmap-api-v2:latest
    environment:
      DB_HOST: postgresql
    ports:
      - 5000:5000
    volumes:
      - penpalmap-api-data:/app/public
    depends_on:
      - postgresql
